imports:
    - { resource: "@SyliusShopApiPlugin/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopApiPlugin/Resources/config/app/sylius_mailer.yml" }

sylius_shop_api:
    view_classes:
        product_variant: App\Service\Sylius\ShopApiPlugin\View\Product\ProductVariantViewExtended
    included_attributes:
        - "capacity"
        - "naturalness"
        - "benefits"
        - "tags"
        - "manual"
        - "yuka_rating"
        - "inci"
        - "concerns"
        - "skin_type"
        - "skin_color"
        - "texture"
        - "hair_type"
        - "ingredients"